### PR TITLE
remove leading backslash from docker.name

### PR DESCRIPTION
**Pull request by bpsizemore**
Issue #7 

cuts off first character of docker.name, which is always a / in the case of our infrastructure. Leaving just the name.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Would you be able to fix up the test as well please?

**Comment by bpsizemore** [comment]
Yep

**Comment by jimmidyson** [comment]
Thanks for the doc updates! LGTM - just waiting on green then will merge.

**Comment by bpsizemore** [comment]
Thanks! Will you push a new release today?

**Comment by jimmidyson** [comment]
Already done :-b

**Pull request merged**
